### ISSUE TITLE
Errores ortográficos en varios enunciados.

### ISSUE THREAD

**Issue by DIODsan** [Ajcaa/PreguntasDeBiologiaReal#2]
Hola hermano, tu trivia está muy buena, lo único que encontré para corregir son errores ortográficos, especialmente quitar la letra 's' de palabras que no la necesitan, por ejemplo 'perdiste', las líneas que encontré son:
#77, #82, #92, #96, #144, #230, #235, #240, #245, #249, #305.

**Comment by Ajcaa** [comment]
Solucionado
